# coding: utf-8

"""
    INDICATE Data Exchange API

    API for exchanging aggregated quality indicator results between INDICATE data providers and the INDICATE hub.  The API has two operations: one for uploading aggregated quality indicator results from a data provider to the hub and one for querying aggregated quality indicator results across all providers. The second operation is intended for use by data providers as well as authorized 3rd-party users. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class AggregationPeriodKind(str, Enum):
    """
    The kind, in particular length, of aggregation period for a single aggregated quality indicator value. 
    """

    """
    allowed enum values
    """
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'
    YEARLY = 'yearly'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AggregationPeriodKind from a JSON string"""
        return cls(json.loads(json_str))


