# coding: utf-8

"""
    INDICATE Data Exchange API

    API for exchanging aggregated quality indicator results between INDICATE data providers and the INDICATE hub.  The API has two operations: one for uploading aggregated quality indicator results from a data provider to the hub and one for querying aggregated quality indicator results across all providers. The second operation is intended for use by data providers as well as authorized 3rd-party users. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IndicatorDefinition(BaseModel):
    """
    IndicatorDefinition
    """ # noqa: E501
    indicator_id: Annotated[int, Field(strict=True, ge=2000000101)] = Field(description="The numeric ID of the OMOP Concept assigned by the INDICATE project for identifying the particular quality indicator. ")
    title: Optional[StrictStr] = Field(default=None, description="The title of the quality indicator. Can be multiple words. ")
    description: Optional[StrictStr] = Field(default=None, description="A short description of the quality indicator. Typically a single paragraph. ")
    __properties: ClassVar[List[str]] = ["indicator_id", "title", "description"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IndicatorDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IndicatorDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "indicator_id": obj.get("indicator_id"),
            "title": obj.get("title"),
            "description": obj.get("description")
        })
        return _obj


