name: publish-container-image

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Build the Docker image
        run: docker build -t ghcr.io/umg-minai/indicate-data-exchange-server:latest -f Containerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push ghcr.io/umg-minai/indicate-data-exchange-server:latest
